/** @type {import('jest').Config} */
const config = {
  // jest-expo lida com o preset correto por plataforma
  preset: "jest-expo",

  // Padrões de arquivos de teste
  testMatch: ["**/__tests__/**/*.{ts,tsx}", "**/*.{spec,test}.{ts,tsx}"],

  testPathIgnorePatterns: [
    "/node_modules/",
    "/e2e/",
    "/.expo/",
    "<rootDir>/_worktrees/",
    "<rootDir>/repos/",
  ],

  // Transformações: jest-expo já configura babel-jest para RN
  transformIgnorePatterns: [
    "node_modules/(?!(" +
      "@react-native|react-native|react-native-.*|expo.*|@expo.*|" +
      "@unimodules.*|unimodules.*|sentry-expo|native-base|" +
      "react-clone-referenced-element|@react-navigation|tamagui|@tamagui" +
      "))",
  ],

  // Módulos que o Node não consegue importar diretamente (assets, etc.)
  moduleNameMapper: {
    "\\.svg$": "<rootDir>/__mocks__/svgMock.ts",
    "\\.(png|jpg|jpeg|gif|webp)$": "<rootDir>/__mocks__/imageMock.ts",
    "^@sentry/react-native$": "<rootDir>/__mocks__/sentryReactNativeMock.ts",
    "^@/(.*)$": "<rootDir>/$1",
    "^~/(.*)$": "<rootDir>/$1",
  },

  // Setup files: configura @testing-library/jest-native matchers
  setupFilesAfterEnv: ["<rootDir>/jest.setup.ts"],

  // Cobertura
  // APP9 baseline: cobertura inicial em fluxo crítico de tema/renderização.
  collectCoverageFrom: [
    "features/tools/services/tools-service.ts",
    "features/tools/hooks/use-tools-catalog-query.ts",
    "app/index.tsx",
    "app/(private)/ferramentas.tsx",
    "core/providers/app-providers.tsx",
    "core/navigation/deep-linking.ts",
    "core/telemetry/app-logger.ts",
    "core/telemetry/domain-loggers.ts",
    "core/telemetry/logging-policy.ts",
    "core/telemetry/operational-context.ts",
    "core/telemetry/sanitization.ts",
    "core/telemetry/use-observability-runtime-bridge.ts",
    "core/telemetry/use-navigation-telemetry.ts",
    "core/performance/performance-budgets.ts",
    "core/performance/performance-clock.ts",
    "core/performance/performance-tracker.ts",
    "core/errors/app-error.ts",
    "core/errors/app-error-boundary.tsx",
    "core/http/api-error.ts",
    "core/http/http-client.ts",
    "core/query/query-feedback-state.ts",
    "core/query/query-client.ts",
    "core/query/query-policy.ts",
    "core/query/prefetch-api-query.ts",
    "core/session/session-policy.ts",
    "core/session/session-storage.ts",
    "core/session/session-store.ts",
    "core/query/retry-policy.ts",
    "core/shell/reachability-service.ts",
    "core/shell/runtime-revalidation.ts",
    "core/shell/use-app-startup.ts",
    "core/shell/use-runtime-lifecycle.ts",
    "app/services/sentry.ts",
    "features/subscription/services/hosted-checkout-service.ts",
    "shared/feature-flags/service.ts",
    "shared/components/app-screen.tsx",
    "shared/components/app-surface-card.tsx",
    "shared/components/app-button.tsx",
    "shared/components/app-input-field.tsx",
    "shared/components/app-key-value-row.tsx",
    "shared/components/app-toggle-row.tsx",
    "shared/components/app-error-notice.tsx",
    "shared/components/app-async-state.tsx",
    "shared/components/app-query-state.tsx",
    "shared/components/async-state-notice.tsx",
    "shared/components/app-skeleton-block.tsx",
    "shared/components/app-text.tsx",
    "shared/components/app-section-header.tsx",
    "shared/components/app-metric-card.tsx",
    "shared/testing/test-providers.tsx",
    "shared/testing/test-query-client.ts",
    "shared/utils/formatters.ts",
    "shared/validators/installment-vs-cash.ts",
    "shared/forms/app-form-field.tsx",
    "shared/forms/apply-api-form-errors.ts",
    "shared/forms/use-form-submit-state.ts",
    "shared/forms/use-form-focus.ts",
    "features/auth/services/password-strength-analyzer.ts",
    "features/auth/components/password-strength-meter.tsx",
    "features/auth/utils/email-mask.ts",
    "features/auth/hooks/use-register-screen-controller.ts",
    "features/auth/hooks/use-confirm-email-pending-controller.ts",
    "features/auth/hooks/use-forgot-password-screen-controller.ts",
    "features/auth/validators.ts",
    "features/dashboard/services/savings-rate-calculator.ts",
    "features/goals/services/goal-progress-calculator.ts",
    "features/goals/hooks/use-goals-screen-controller.ts",
    "core/navigation/auth-redirect-context.ts",
    "features/subscription/services/subscription-plan-comparator.ts",
    "features/subscription/hooks/use-checkout-flow.ts",
    "features/subscription/hooks/use-subscription-screen-controller.ts",
    "features/entitlements/hooks/use-entitlements-foreground-refresh.ts",
    "features/shared-entries/services/shared-entries-classifier.ts",
    "features/shared-entries/hooks/use-shared-entries-screen-controller.ts",
    "features/auth/hooks/use-reset-password-screen-controller.ts",
    "features/goals/hooks/use-goals-mutations.ts",
    "features/goals/validators.ts",
    "features/transactions/validators.ts",
    "features/wallet/validators.ts",
    "features/wallet/hooks/use-wallet-mutations.ts",
    "features/wallet/hooks/use-wallet-screen-controller.ts",
    "features/user-profile/validators.ts",
    "features/user-profile/hooks/use-user-profile-screen-controller.ts",
    "features/fiscal/validators.ts",
    "features/fiscal/hooks/use-fiscal-screen-controller.ts",
    "features/dashboard/services/category-ranker.ts",
    "features/dashboard/services/trends-chart-projector.ts",
    "features/questionnaire/hooks/use-questionnaire-screen-controller.ts",
    "features/alerts/components/alert-record-card.tsx",
    "features/alerts/components/alert-preference-row.tsx",
    "features/entitlements/components/paywall-gate.tsx",
    "features/entitlements/hooks/use-feature-access.ts",
    "features/fiscal/services/fiscal-service.ts",
    "features/fiscal/hooks/use-fiscal-query.ts",
    "features/fiscal/hooks/use-fiscal-mutations.ts",
    "features/questionnaire/services/questionnaire-service.ts",
    "features/questionnaire/hooks/use-questionnaire-query.ts",
    "features/questionnaire/hooks/use-questionnaire-mutations.ts",
    "features/shared-entries/services/shared-entries-service.ts",
    "features/shared-entries/hooks/use-shared-entries-query.ts",
    "features/shared-entries/hooks/use-shared-entries-mutations.ts",
    "features/subscription/components/upgrade-cta.tsx",
    "features/tools/services/installment-vs-cash-service.ts",
    "features/tools/hooks/use-installment-vs-cash-history-query.ts",
    "features/tools/components/installment-vs-cash-form.tsx",
    "features/tools/components/installment-vs-cash-history-list.tsx",
    "features/tools/components/installment-vs-cash-result-card.tsx",
    "features/transactions/services/transactions-service.ts",
    "features/transactions/hooks/use-transactions-query.ts",
    "features/transactions/hooks/use-transaction-mutations.ts",
    "features/transactions/hooks/use-transactions-screen-controller.ts",
    "features/user-profile/services/user-profile-service.ts",
    "features/user-profile/hooks/use-user-profile-query.ts",
    "features/user-profile/hooks/use-user-profile-mutations.ts",
    "app/(private)/installment-vs-cash.tsx",
    "features/dashboard/services/survival-index-calculator.ts",
    "features/wallet/validators-operations.ts",
    "features/wallet/hooks/use-wallet-operations-mutations.ts",
    "features/wallet/hooks/use-wallet-operations-query.ts",
    "features/wallet/hooks/use-wallet-operations-screen-controller.ts",
    "features/wallet/services/brapi-service.ts",
    "features/wallet/hooks/use-brapi-queries.ts",
    "features/wallet/hooks/use-wallet-live-quotes.ts",
    "features/wallet/components/ticker-autocomplete.tsx",
    "features/tags/validators.ts",
    "features/tags/hooks/use-tags-mutations.ts",
    "features/tags/hooks/use-tags-screen-controller.ts",
    "features/accounts/validators.ts",
    "features/accounts/hooks/use-accounts-mutations.ts",
    "features/accounts/hooks/use-accounts-screen-controller.ts",
    "features/credit-cards/validators.ts",
    "features/credit-cards/hooks/use-credit-cards-mutations.ts",
    "features/credit-cards/hooks/use-credit-cards-screen-controller.ts",
    "features/budgets/validators.ts",
    "features/budgets/hooks/use-budgets-mutations.ts",
    "features/budgets/hooks/use-budgets-screen-controller.ts",
    "features/focus/services/focus-metric-calculator.ts",
    "features/focus/hooks/use-focus-screen-controller.ts",
    "features/onboarding/validators.ts",
    "features/onboarding/hooks/use-onboarding-screen-controller.ts",
    "features/goals/validators-simulator.ts",
    "features/goals/hooks/use-goal-simulator-screen-controller.ts",
    "features/transactions/hooks/use-transactions-trash-screen-controller.ts",
    "features/user-profile/validators-salary-sim.ts",
    "features/user-profile/hooks/use-salary-simulator-screen-controller.ts",
    "features/user-profile/hooks/use-notification-preferences-screen-controller.ts",
    "core/security/biometric-gate.ts",
    "core/security/integrity-check.ts",
    "core/security/ssl-pinning.ts",
    "core/security/turnstile-config.ts",
    "core/security/use-biometric-gate.ts",
    "core/shell/use-resolved-theme.ts",
    "core/query/create-api-mutation.ts",
    "features/auth/components/turnstile-challenge.tsx",
    "features/auth/hooks/use-resend-confirmation-screen-controller.ts",
    "features/auth/screens/resend-confirmation-screen.tsx",
    "features/dashboard/services/period-comparison.ts",
    "features/dashboard/components/dashboard-comparison-card.tsx",
    "features/subscription/components/checkout-outcome-card.tsx",
    "features/transactions/services/calendar-grid.ts",
    "features/transactions/services/calendar-markers.ts",
    "features/transactions/services/transactions-export-service.ts",
    "features/transactions/components/financial-calendar.tsx",
    "features/user-profile/components/appearance-section.tsx",
    "features/user-profile/components/language-section.tsx",
    "shared/components/app-empty-state.tsx",
    "shared/components/app-image.tsx",
    "shared/feedback/haptics.ts",
    "shared/hooks/use-list-refresh.ts",
    "shared/hooks/use-prefetch-on-press.ts",
    "shared/i18n/index.ts",
    "shared/skeletons/alerts-list-skeleton.tsx",
    "shared/skeletons/budgets-list-skeleton.tsx",
    "shared/skeletons/dashboard-skeleton.tsx",
    "shared/skeletons/fiscal-documents-skeleton.tsx",
    "shared/skeletons/goal-list-skeleton.tsx",
    "shared/skeletons/metric-grid-skeleton.tsx",
    "shared/skeletons/transaction-list-skeleton.tsx",
    "shared/skeletons/wallet-entry-list-skeleton.tsx",
    "!**/*.d.ts",
    "!**/*.config.{ts,js}",
  ],

  coverageThreshold: {
    global: {
      // Lines / functions / statements stay at the platform-wide 85%.
      // Branches is held at 80%: UI-heavy files have many one-off
      // theme-fallback branches (?.val ?? '#hex') that swallow most
      // of the unreached branch counter for marginal real-world
      // value. The hard gate stays on the other three metrics.
      lines: 85,
      functions: 85,
      branches: 80,
      statements: 85,
    },
  },

  coverageReporters: ["text", "json", "lcov", "html"],
  coverageDirectory: "coverage",

  testTimeout: 10_000,
};

module.exports = config;
