export const apiEndpointCatalog = {
  auth: [
    "POST /auth/register",
    "POST /auth/login",
    "POST /auth/refresh",
    "POST /auth/logout",
    "POST /auth/password/forgot",
    "POST /auth/password/reset",
    "POST /auth/email/confirm",
    "POST /auth/email/resend",
  ],
  user: [
    "GET /user/me",
    "DELETE /user/me",
    "GET /user/profile",
    "PUT /user/profile",
    "GET /user/profile/questionnaire",
    "POST /user/profile/questionnaire",
    "POST /user/simulate-salary-increase",
    "GET /user/bootstrap",
  ],
  dashboard: [
    "GET /dashboard/overview",
    "GET /dashboard/trends",
  ],
  goals: [
    "GET /goals",
    "POST /goals",
    "POST /goals/simulate",
    "GET /goals/{goal_id}",
    "PATCH /goals/{goal_id}",
    "DELETE /goals/{goal_id}",
    "GET /goals/{goal_id}/plan",
  ],
  transactions: [
    "GET /transactions",
    "GET /transactions/list",
    "GET /transactions/dashboard",
    "GET /transactions/summary",
    "GET /transactions/deleted",
    "GET /transactions/due-range",
    "GET /transactions/expenses",
    "POST /transactions",
    "GET /transactions/{transaction_id}",
    "PUT /transactions/{transaction_id}",
    "DELETE /transactions/{transaction_id}",
    "PATCH /transactions/{transaction_id}/force",
    "PATCH /transactions/restore/{transaction_id}",
  ],
  wallet: [
    "GET /wallet",
    "POST /wallet",
    "GET /wallet/valuation",
    "GET /wallet/valuation/history",
    "GET /wallet/{investment_id}",
    "PATCH /wallet/{investment_id}",
    "DELETE /wallet/{investment_id}",
    "GET /wallet/{investment_id}/history",
    "POST /wallet/{investment_id}/operations",
    "GET /wallet/{investment_id}/operations",
    "PATCH /wallet/{investment_id}/operations/{operation_id}",
    "DELETE /wallet/{investment_id}/operations/{operation_id}",
    "GET /wallet/{investment_id}/operations/summary",
    "GET /wallet/{investment_id}/operations/position",
    "GET /wallet/{investment_id}/operations/invested-amount",
    "GET /wallet/{investment_id}/valuation",
  ],
  alerts: [
    "GET /alerts",
    "POST /alerts/{alertId}/read",
    "DELETE /alerts/{alertId}",
    "GET /alerts/preferences",
    "PUT /alerts/preferences/{category}",
  ],
  sharedEntries: [
    "GET /shared-entries/by-me",
    "GET /shared-entries/with-me",
    "POST /shared-entries",
    "DELETE /shared-entries/{sharedEntryId}",
    "GET /shared-entries/invitations",
    "POST /shared-entries/invitations",
    "POST /shared-entries/invitations/{token}/accept",
    "DELETE /shared-entries/invitations/{invitationId}",
  ],
  entitlements: [
    "GET /entitlements/check",
  ],
  fiscal: [
    "POST /fiscal/csv/upload",
    "POST /fiscal/csv/confirm",
    "GET /fiscal/receivables",
    "POST /fiscal/receivables",
    "PATCH /fiscal/receivables/{entryId}/receive",
    "DELETE /fiscal/receivables/{entryId}",
    "GET /fiscal/receivables/summary",
    "GET /fiscal/fiscal-documents",
    "POST /fiscal/fiscal-documents",
  ],
  simulations: [
    "GET /simulations",
    "POST /simulations/installment-vs-cash",
    "POST /simulations/installment-vs-cash/calculate",
    "POST /simulations/{simulation_id}/goal",
    "POST /simulations/{simulation_id}/planned-expense",
  ],
  subscriptions: [
    "GET /subscriptions/plans",
    "GET /subscriptions/me",
    "POST /subscriptions/checkout",
    "POST /subscriptions/cancel",
    "POST /subscriptions/trial",
    "POST /subscriptions/webhook",
  ],
  observability: [
    "GET /ops/observability",
    "GET /ops/metrics",
  ],
} as const;

export type ApiDomain = keyof typeof apiEndpointCatalog;
